apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codegen-260201-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/codegen-260201/overlays/development
    repoURL: https://github.com/fpetk/codegen-260201-gitops.git
    targetRevision: main
  destination:
    namespace: ai-software-templates-dev
    server: https://api.x85kd-2vtqw-hse.76uv.p3.openshiftapps.com:443
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
