apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: codegen-260201-gitops
  description: This is GitOps manifest for codegen-260201   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=codegen-260201
    janus-idp.io/tekton: codegen-260201 
    backstage.io/kubernetes-id: codegen-260201 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:codegen-260201  
